apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.nginx.name}}-deployment
  # namespace

spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      server: {{ .Values.nginx.name}}
  template:
    metadata:
      labels:
        server: {{ .Values.nginx.name}}
    spec:
      containers:
        - name: {{ .Values.nginx.name}}
          image: {{ .Values.nginx.image.name}}:{{ .Values.nginx.image.tag}}
          imagePullPolicy: Never #Use docker local
          ports:
            - containerPort: {{ .Values.nginx.image.exposedPort}}
