image: docker:19

services:
  - docker:stable-dind

stages:
  - test
  - release

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - apk --update add nodejs npm
  - npm install

test:
  stage: test
  script:
    - npm run test:coverage

release-image:
  stage: release
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        ENV: 'local'
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        ENV: 'production'
  script:
    - npm run build:$ENV
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
