version: '3'

services:
  nodeserver:
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
    ports:
      - '8080:8080'
    container_name: nodeserver
    hostname: nodeserver
    # networks:
    #   - example-net
  nginx:
    restart: always
    build:
      context: ./
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - '80:80'
    container_name: nginx
    hostname: nginx
# networks:
#   example-net:
#     external: true
