version: '3'

services:
  nodejs-app:
    build:
      context: ./.docker
      dockerfile: ./nodejsdockerfile
    container_name: nodejsserver
    hostname: nodejsserver
    ports:
      - '8080:8080'
    networks:
      - example-net
networks:
  example-net:
    external: true
